config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'about#index'

  post '/signup', to: 'registrations#create'
  get '/signup', to: 'registrations#new'

  get 'password', to: 'passwords#edit'
  patch 'password', to: 'passwords#update'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new', as: :password_reset
  post 'password/reset/send', to: 'password_resets#reset_send', as: :password_reset_send
  get 'password/reset/edit', to: 'password_resets#edit', as: :password_reset_edit
  patch 'password/reset/update', to: 'password_resets#update', as: :password_reset_update

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_commit :donwcase_email, only: %i[new create edit update]

  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :email, format: {
    with: URI::MailTo::EMAIL_REGEXP, message: 'is invalid'
  }
  validates :password, length: { minimum: 8, maximum: 40 }

  private

  def donwcase_email
    self.email = email.downcase
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authentication!
    unless logged_in?
      flash[:danger] = "You aren't authorized to visit that page."
      redirect_to signin_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    if logged_in?
      flash[:warning] = 'Edit your password'
      redirect_to root_path
    end
  end

  def reset_send
    @user = User.find_by(email: params[:email])
    PasswordMailer.with(user: @user).reset.deliver_later if @user.present?
    flash[:success] = 'If that account was found with that email, We will send a password reset link.'
    redirect_to root_path
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    flash[:danger] = 'Invalid token reset password again.'
    redirect_to signin_path
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      flash[:success] = 'Your passowrd was reset successfully. Please signin.'
      redirect_to signin_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authentication!, only: %i[edit update]

  def edit; end

  def update
    if current_user.update(password_params)
      flash[:success] = 'Password updated successfully.'
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    if logged_in?
      flash[:warning] = 'You\'ve already signed up.'
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User registered successfully.'
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      flash[:warning] = 'You\'ve already signed in.'
      redirect_to root_path
    end
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Signin successfully.'
      redirect_to root_path
    else
      flash[:danger] = 'Invalid Email or Passowrd.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil

    flash[:danger] = 'Signout successfully'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> This is about page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduled Tweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>    
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1> This is the main page</h1>
</div>

<% if current_user %>
  <%= current_user.email %>
<% end %>

app/views/password_resets/edit.html.erb
<div class="container">
  <h1> Reset your Password</h1>

  <%= form_with(model: @user, url: password_reset_update_path(token: params[:token])) do |form| %> 
  <%= render 'shared/errors', object: @user %>      
    <div class="mb-3">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control", required: true %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control", required: true %>
    </div>
    <%= form.submit "Reset Password", class: "btn btn-lg btn-success" %>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="container">
  <h1>Forgot your password?</h1>
  
  <%= form_with url: password_reset_send_path do |form| %>        
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control", required: true %>
    </div>    
    <%= form.submit "Reset password", class: "btn btn-lg btn-success" %>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, id: "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.present? %>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
<% end %>

app/views/shared/_link.html.erb
<div class="forgot-password">
  <p>
    <%= link_to password_reset_path do %>
      Forgot password
    <% end %>
  </p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      Scheduled Tweets
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link active", aria: {current: "page"} do %>
            Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to about_path, class: "nav-link" do %>
            About
          <% end %>
        </li>
        
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to password_path, class: "nav-link" do %>
              Edit Password
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to signout_path, class: "nav-link", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              Sign out
            <% end %>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to signup_path, class: "nav-link" do %>
            Sign up
          <% end %>
        </li>
          <li class="nav-item">
            <%= link_to signin_path, class: "nav-link" do %>
              Sign in
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>